---
version: "3"
volumes:
  home:
    name: jenkins_home

services:
  app:
    image: self/jenkins:${DOCKER_TAG}
    build:
      context: .
      args:
        - GID=${GID}
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/lib/jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
